tags:
  name: jobdictionary
  description: 직업 사전 API

/jobguide/jobdictinfo:
  get:
    tags:
      - jobdictionary
    summary: 직업 정보 조회
    operationId: getJobDictInfo
    responses:
      '200':
        description: 성공 - 직업 정보 조회 성공
        content:
          application/json:
            example:
              isSuccess: true
              code: 1000
              message: 성공
              result:
                - jobName: '개발자'
                  jobCode: 'DEV'
                - jobName: '디자이너'
                  jobCode: 'DES'
                # ... (직업 정보 추가)
      '9004':
        description: 직업 정보가 없음
        content:
          application/json:
            example:
              isSuccess: false
              code: 9004
              message: 직업 정보가 없습니다.
      '500':
        description: 내부 서버 오류
        content:
          application/json:
            example:
              isSuccess: false
              code: 500
              message: 내부 서버 오류

/jobguide/jobdetails/{jobname}:
  get:
    tags:
      - jobdictionary
    summary: 직업 세부 정보 조회
    operationId: getJobDetails
    parameters:
      - in: path
        name: jobname
        required: true
        description: 세부 정보를 조회할 직업 이름
        schema:
          type: string
    responses:
      '200':
        description: 성공 - 직업 세부 정보 조회 성공
        content:
          application/json:
            example:
              isSuccess: true
              code: 1000
              message: 성공
              result:
                jobName: '개발자'
                jobCode: 'DEV'
                jobDescription: '소프트웨어 개발을 담당하는 직업입니다.'
                jobImage: 'https://example.com/dev-image.jpg'
      '9007':
        description: 직업 세부 정보가 없음
        content:
          application/json:
            example:
              isSuccess: false
              code: 9007
              message: 직업 세부 정보가 없습니다.
      '500':
        description: 내부 서버 오류
        content:
          application/json:
            example:
              isSuccess: false
              code: 500
              message: 내부 서버 오류
/jobguide/interestjob/{jobname}:
  post:
    tags:
      - jobdictionary
    summary: 관심 직무 추가
    operationId: addInterestJob
    parameters:
      - in: path
        name: jobname
        required: true
        description: 직업 이름
        schema:
          type: string
    responses:
      '1000':
        description: 성공 - 관심 직무 추가 성공
        content:
          application/json:
            example:
              isSuccess: true
              code: 1000
              message: '관심 직무가 추가되었습니다.'
      '9001':
        description: 실패 - 이미 관심 직무가 등록되어 있음
        content:
          application/json:
            example:
              isSuccess: false
              code: 9001
              message: '이미 관심 직무가 등록되어 있습니다.'
      '9002':
        description: 실패 - 최대 한 개의 관심 직무 등록이 가능함
        content:
          application/json:
            example:
              isSuccess: false
              code: 9002
              message: '최대 한 개의 관심 직무 등록이 가능합니다.'
      '9003':
        description: 실패 - 해당 직업은 존재하지 않음
        content:
          application/json:
            example:
              isSuccess: false
              code: 9003
              message: '해당 직업은 존재하지 않습니다.'
      '500':
        description: 실패 - 내부 서버 오류
        content:
          application/json:
            example:
              isSuccess: false
              code: 500
              message: '내부 서버 오류'
/jobguide/interestjobinfo:
  get:
    tags:
      - jobdictionary
    summary: 유저 관심 직무 조회
    operationId: getMyInterestJobInfo
    responses:
      '1000':
        description: 성공 - 유저의 관심 직무 정보 조회 성공
        content:
          application/json:
            example:
              isSuccess: true
              code: 1000
              message: '성공'
              data:
                - '소프트웨어 개발자'
                - 'UX 디자이너'
      '3000':
        description: 실패 - JWT 토큰 검증 실패
        content:
          application/json:
            example:
              isSuccess: false
              code: 3000
              message: 'JWT 토큰 검증 실패'
      '9003':
        description: 실패 - 관심 직무 정보를 찾을 수 없음
        content:
          application/json:
            example:
              isSuccess: false
              code: 9003
              message: '관심 직무 정보를 찾을 수 없습니다.'
      '500':
        description: 실패 - 내부 서버 오류
        content:
          application/json:
            example:
              isSuccess: false
              code: 500
              message: '내부 서버 오류'
