tags:
  name: jobdictionary
  description: 직업 사전 API

/jobguide/jobdictinfo:
  get:
    tags:
      - jobdictionary
    summary: 직업 정보 조회
    operationId: getJobDictInfo
    responses:
      '200':
        description: 성공 - 직업 정보 조회 성공
        content:
          application/json:
            example:
              isSuccess: true
              code: 1000
              message: 성공
              result:
                - jobName: '정보보안 전문가'
                - jobName: '소프트웨어 개발자'
                - jobName: '데이터 분석가'
                - jobName: '클라우드 엔지니어'
                # ... (직업 정보 추가)
      '9004':
        description: 직업 정보가 없음
        content:
          application/json:
            example:
              isSuccess: false
              code: 9004
              message: 직업 정보가 없습니다.
      '500':
        description: 내부 서버 오류
        content:
          application/json:
            example:
              isSuccess: false
              code: 500
              message: 내부 서버 오류

/jobguide/jobdetails/{jobname}:
  get:
    tags:
      - jobdictionary
    summary: 직업 세부 정보 조회
    operationId: getJobDetails
    parameters:
      - in: path
        name: jobname
        required: true
        description: 세부 정보를 조회할 직업 이름
        schema:
          type: string
    responses:
      '200':
        description: 성공 - 직업 세부 정보 조회 성공
        content:
          application/json:
            example:
              isSuccess: true
              code: 1000
              message: 성공
              result:
                jobName: '정보보안 전문가'
                jobDescription: '
                정보보안 전문가란?
                해커의 침입과 각종 바이러스 발생에 대비해 전산망을 전문적으로 보안 및 유지하는 사람
                서버의 하드웨어와 소프트웨어에 대한 기술을 바탕으로 향후 일어날 수 있는 보안상 문제를 해결

                정보보안 전문가의 업무

                1. 네트워크의 취약 요소를 파악해 대비책 마련
                2. 인터넷망을 통한 외부로부터의 불법적인 침입 대비
                3. 불법침입을 탐지하기 위한 시스템 개발
                4. 컴퓨터 바이러스 백신 프로그램 개발 및 보급
                5. 컴퓨터 바이러스에 감염된 데이터 복구 등 '
                jobImage: 'https://example.com/dev-image.jpg'
      '9007':
        description: 직업 세부 정보가 없음
        content:
          application/json:
            example:
              isSuccess: false
              code: 9007
              message: 직업 세부 정보가 없습니다.
      '500':
        description: 내부 서버 오류
        content:
          application/json:
            example:
              isSuccess: false
              code: 500
              message: 내부 서버 오류
/jobguide/interestjob/{jobname}:
  post:
    tags:
      - jobdictionary
    summary: 관심 직무 추가
    operationId: addInterestJob
    parameters:
      - in: path
        name: jobname
        required: true
        description: 직업 이름
        schema:
          type: string
    responses:
      '1000':
        description: 성공 - 관심 직무 추가 성공
        content:
          application/json:
            example:
              isSuccess: true
              code: 1000
              message: '관심 직무가 추가되었습니다.'
      '9001':
        description: 실패 - 이미 관심 직무가 등록되어 있음
        content:
          application/json:
            example:
              isSuccess: false
              code: 9001
              message: '이미 관심 직무가 등록되어 있습니다.'
      '9002':
        description: 실패 - 최대 한 개의 관심 직무 등록이 가능함
        content:
          application/json:
            example:
              isSuccess: false
              code: 9002
              message: '최대 한 개의 관심 직무 등록이 가능합니다.'
      '9003':
        description: 실패 - 해당 직업은 존재하지 않음
        content:
          application/json:
            example:
              isSuccess: false
              code: 9003
              message: '해당 직업은 존재하지 않습니다.'
      '500':
        description: 실패 - 내부 서버 오류
        content:
          application/json:
            example:
              isSuccess: false
              code: 500
              message: '내부 서버 오류'
/jobguide/interestjobinfo:
  get:
    tags:
      - jobdictionary
    summary: 유저 관심 직무 조회
    operationId: getMyInterestJobInfo
    responses:
      '1000':
        description: 성공 - 유저의 관심 직무 정보 조회 성공
        content:
          application/json:
            example:
              isSuccess: true
              code: 1000
              message: '성공'
              data:
                - '소프트웨어 개발자'
                - 'UX 디자이너'
      '3000':
        description: 실패 - JWT 토큰 검증 실패
        content:
          application/json:
            example:
              isSuccess: false
              code: 3000
              message: 'JWT 토큰 검증 실패'
      '9003':
        description: 실패 - 관심 직무 정보를 찾을 수 없음
        content:
          application/json:
            example:
              isSuccess: false
              code: 9003
              message: '관심 직무 정보를 찾을 수 없습니다.'
      '500':
        description: 실패 - 내부 서버 오류
        content:
          application/json:
            example:
              isSuccess: false
              code: 500
              message: '내부 서버 오류'
