openapi: 3.0.0
info:
  title: 직업 사전 API
  version: '1.0'
tags:
  - name: jobdictionary
    description: 직업 사전 API

paths:
  /jobguide/jobdictinfo:
    get:
      tags:
        - jobdictionary
      summary: 직업 정보 조회
      operationId: getJobDictInfo
      responses:
        '200':
          description: 성공 - 직업 정보 조회 성공
          content:
            application/json:
              example:
                isSuccess: true
                code: 1000
                message: 성공
                result:
                  - jobName: '정보보안 전문가'
                  - jobName: '소프트웨어 개발자'
                  - jobName: '데이터 분석가'
                  - jobName: '클라우드 엔지니어'
        '9004':
          description: 직업 정보가 없음
          content:
            application/json:
              example:
                isSuccess: false
                code: 9004
                message: 직업 정보가 없습니다.
        '500':
          description: 내부 서버 오류
          content:
            application/json:
              example:
                isSuccess: false
                code: 500
                message: 내부 서버 오류

  /jobguide/jobdetails/{jobname}:
    get:
      tags:
        - jobdictionary
      summary: 직업 세부 정보 조회
      operationId: getJobDetails
      parameters:
        - in: path
          name: jobname
          required: true
          description: 세부 정보를 조회할 직업 이름
          schema:
            type: string
      responses:
        '200':
          description: 성공 - 직업 세부 정보 조회 성공
          content:
            application/json:
              example:
                isSuccess: true
                code: 1000
                message: 성공
                result:
                  jobName: '정보보안 전문가'
                  jobDescription: [직업 설명]
                  jobImage: 'https://example.com/dev-image.jpg'
        '9007':
          description: 이미지 정보 조회 실패
          content:
            application/json:
              example:
                isSuccess: false
                code: 9007
                message: 이미지 정보를 가져오는데 실패했습니다.
        '9008':
          description: 직업 세부 정보가 없음
          content:
            application/json:
              example:
                isSuccess: false
                code: 9008
                message: 직업 세부 정보가 없습니다.
        '500':
          description: 내부 서버 오류
          content:
            application/json:
              example:
                isSuccess: false
                code: 500
                message: 내부 서버 오류

  /jobguide/interestjobs:
    post:
      tags:
        - jobdictionary
      summary: 관심 직무 추가
      operationId: addInterestJob
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - jobname
              properties:
                jobname:
                  type: string
      responses:
        '200':
          description: 성공 - 관심 직무 추가 성공
          content:
            application/json:
              example:
                isSuccess: true
                code: 1000
                message: '관심 직무가 추가되었습니다.'
        '9001':
          description: 실패 - 이미 관심 직무가 등록되어 있음
          content:
            application/json:
              example:
                isSuccess: false
                code: 9001
                message: '이미 관심 직무가 등록되어 있습니다.'
        '9006':
          description: 실패 - 관심 직무를 추가 실패
          content:
            application/json:
              example:
                isSuccess: false
                code: 9006
                message: '관심 직무를 추가하는데 실패했습니다.'
        '500':
          description: 실패 - 내부 서버 오류
          content:
            application/json:
              example:
                isSuccess: false
                code: 500
                message: '내부 서버 오류'

  /jobguide/interestjobs/{jobname}:
    put:
      tags:
        - jobdictionary
      summary: 관심 직무 수정
      operationId: updateInterestJob
      parameters:
        - in: path
          name: jobname
          required: true
          description: 수정할 관심 직무 이름
          schema:
            type: string
      responses:
        '200':
          description: 성공 - 관심 직무 수정 성공
          content:
            application/json:
              example:
                isSuccess: true
                code: 1000
                message: '관심 직무가 업데이트되었습니다.'
        '9010':
          description: 실패 - 관심 직무 수정 실패
          content:
            application/json:
              example:
                isSuccess: false
                code: 9010
                message: '관심 직무를 수정하지 못했습니다.'
        '500':
          description: 실패 - 내부 서버 오류
          content:
            application/json:
              example:
                isSuccess: false
                code: 500
                message: '내부 서버 오류'
