# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  SSH:
    runs-on: ubuntu-20.04

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          uername: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script:
            cd ~/backend
            pm2 kill
            git pull
            npm i
            cd ~/backend/src
            pm2 start app.js
